### ISSUE TITLE
Python 3.6 AWS Lambda runtime - EOL in 2022

### ISSUE THREAD

**Issue by fred-vogt-dod** [AndrewFarley/AWS-Automated-Daily-Instance-AMI-Snapshots#16]
The lambda runtime should be updated to something newer than `3.6` 
- `3.7`, `3.8`, or `3.9`.

```
July 18, 2022 => end of security updates
Aug 17, 2022  => end of create, update access
```

![Screen Shot 2022-05-05 at 3 31 33 PM](https://user-images.githubusercontent.com/70547635/167035738-40a0fbce-370c-4e8a-94f0-28d94a21cc3d.png)
![Screen Shot 2022-05-05 at 3 31 39 PM](https://user-images.githubusercontent.com/70547635/167035745-1e005c0b-c501-4514-a9cf-e31836f16540.png)

## Links
* https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html - `Runtime deprecation policy` section
* https://peps.python.org/pep-0494/
  * `3.6.15 final: 2021-09-04` => last security-only release

**Comment by AndrewFarley** [comment]
Fixed in https://github.com/AndrewFarley/AWS-Automated-Daily-Instance-AMI-Snapshots/commit/00bce1faba1dd47e126a7243c708b611623b1ad1
