### ISSUE TITLE
Modification regarding volumes only

### ISSUE THREAD

**Issue by milvain** [AndrewFarley/AWS-Automated-Daily-Instance-AMI-Snapshots#9]
Hi Andrew,
Many thanks for your awesome code!!
I would like a similar code but only on volumes. Take a snapshot every week and delete the previous. I am in the Paris region and we don't have this native function.
Could you please help me to modify your code regarding only volumes tagged Backup:true? I'm not interested to create an AMI only a backup of EBS data volume.
Many thanks

**Comment by AndrewFarley** [comment]
Hey, I'm sorry I didn't see your request until now.  It doesn't auto-watch me on my own repositories I just enabled it, lol.  This is a great feature request.  I'll see what I can do for you!  :)  I'll work on it now maybe have something for you tomorrow.

**Comment by AndrewFarley** [comment]
@milvain Done!  :)  2 hours of work.  :P  Enjoy!

**Comment by milvain** [comment]
Many thanks Andrew, I try now!
